apiVersion: v1
kind: ServiceAccount
metadata:
  name: filter-sa
  labels:
    app: filter-logs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filter-role
  labels:
    app: filter-logs
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filter-rb
  labels:
    app: filter-logs
subjects:
- kind: ServiceAccount
  name: filter-sa
roleRef:
  kind: Role
  name: filter-role
  apiGroup: rbac.authorization.k8s.io
